FUND_COMPANIES = {
    "Alger",
    "ALPS",
    "AMG Funds",
    "AQR Funds",
    "Aberdeen",
    "AllianceBernstein",
    "Allianz Funds",
    "American Beacon",
    "American Century Investments",
    "American Funds",
    "Aquila",
    "Artisan",
    "BMO Funds",
    "BNY Mellon Funds",
    "Baird",
    "Barclays Funds",
    "Barings Funds",
    "Baron Capital Group",
    "BlackRock",
    "Brown Advisory Funds",
    "Calamos",
    "Calvert Investments",
    "Catalyst Mutual Funds",
    "Cohen & Steers",
    "Columbia",
    "Commerz Funds Solutions SA",
    "Commerzbank AG, Frankfurt am Main",
    "Davis Funds",
    "Delaware Investments",
    "Deutsche Asset Management",
    "Deutsche Bank AG",
    "Diamond Hill Funds",
    "Dimensional Fund Advisors",
    "Direxion Funds",
    "DoubleLine",
    "Dreyfus",
    "Dunham Funds",
    "Eagle Funds",
    "Eaton Vance",
    "Federated",
    "Fidelity Investments",
    "First Investors",
    "First Trust",
    "Flexshares Trust",
    "Franklin Templeton Investments",
    "GMO",
    "Gabelli",
    "Global X Funds",
    "Goldman Sachs",
    "Great-West Funds",
    "Guggenheim Investments",
    "GuideStone Funds",
    "HSBC",
    "Hancock Horizon",
    "Harbor",
    "Hartford Mutual Funds",
    "Henderson Global",
    "Hennessy",
    "Highland Funds",
    "ICON Funds",
    "Invesco",
    "Ivy Funds",
    "JPMorgan",
    "Janus",
    "John Hancock",
    "Lazard",
    "Legg Mason",
    "Lord Abbett",
    "MFS",
    "Madison Funds",
    "MainStay",
    "Manning & Napier",
    "Market Vectors",
    "MassMutual",
    "Matthews Asia Funds",
    "Morgan Stanley",
    "Nationwide",
    "Natixis Funds",
    "Neuberger Berman",
    "Northern Funds",
    "Nuveen",
    "OppenheimerFunds",
    "PNC Funds",
    "Pacific funds series trust",
    "Pax World",
    "Paydenfunds",
    "Pimco",
    "Pioneer Investments",
    "PowerShares",
    "Principal Funds",
    "ProFunds",
    "ProShares",
    "Prudential Investments",
    "Putnam",
    "RBC Global Asset Management",
    "RidgeWorth",
    "Royce",
    "Russell",
    "Rydex Funds",
    "SEI",
    "SPDR State Street Global Advisors",
    "Salient Funds",
    "Saratoga",
    "Schwab Funds",
    "Sentinel",
    "Shelton Capital Management",
    "State Farm",
    "State Street Global Advisors (Chicago)",
    "Sterling Capital Funds",
    "SunAmerica",
    "T. Rowe Price",
    "TCW",
    "TIAA-CREF Asset Management",
    "Teton Westwood Funds",
    "Thornburg",
    "Thrivent",
    "Timothy Plan",
    "Touchstone",
    "Transamerica",
    "UBS",
    "UBS Group AG",
    "USAA",
    "VALIC",
    "Vanguard",
    "Vantagepoint Funds",
    "Victory",
    "Virtus",
    "Voya",
    "Waddell & Reed",
    "Wasatch",
    "Wells Fargo Funds",
    "William Blair",
    "WisdomTree",
}
