FUND_CATEGORIES = {
    "Allocation - 15% to 30% Equity",
    "Allocation - 30% to 50% Equity",
    "Allocation - 50% to 70% Equity",
    "Allocation - 70% to 85% Equity",
    "Allocation - 85%+ Equity",
    "Bank Loan",
    "Bear Market",
    "China Region",
    "Commodities Agriculture",
    "Commodities Broad Basket",
    "Convertibles",
    "Corporate Bond",
    "Diversified Emerging Mkts",
    "Diversified Pacific/Asia",
    "Emerging Markets Bond",
    "Emerging-Markets Local-Currency Bond",
    "Energy Limited Partnership",
    "Equity Energy",
    "Equity Precious Metals",
    "Europe Stock",
    "Financial",
    "Foreign Large Blend",
    "Foreign Large Growth",
    "Foreign Large Value",
    "Foreign Small/Mid Blend",
    "Foreign Small/Mid Growth",
    "Foreign Small/Mid Value",
    "Global Real Estate",
    "Health",
    "High Yield Bond",
    "High Yield Muni",
    "Inflation-Protected Bond",
    "Infrastructure",
    "Intermediate Government",
    "Intermediate-Term Bond",
    "Japan Stock",
    "Large Blend",
    "Large Growth",
    "Large Value",
    "Long Government",
    "Long-Short Credit",
    "Long-Short Equity",
    "Long-Term Bond",
    "Managed Futures",
    "Market Neutral",
    "Mid-Cap Blend",
    "Mid-Cap Growth",
    "Mid-Cap Value",
    "Miscellaneous Region",
    "Multialternative",
    "Multicurrency",
    "Multisector Bond",
    "Muni California Intermediate",
    "Muni California Long",
    "Muni Massachusetts",
    "Muni Minnesota",
    "Muni National Interm",
    "Muni National Long",
    "Muni National Short",
    "Muni New Jersey",
    "Muni New York Intermediate",
    "Muni New York Long",
    "Muni Ohio",
    "Muni Pennsylvania",
    "Muni Single State Interm",
    "Muni Single State Long",
    "Muni Single State Short",
    "Natural Resources",
    "Nontraditional Bond",
    "Option Writing",
    "Other",
    "Other Allocation",
    "Pacific/Asia ex-Japan Stk",
    "Preferred Stock",
    "Real Estate",
    "Short Government",
    "Short-Term Bond",
    "Small Blend",
    "Small Growth",
    "Small Value",
    "Tactical Allocation",
    "Target-Date 2000-2010",
    "Target-Date 2015",
    "Target-Date 2020",
    "Target-Date 2025",
    "Target-Date 2030",
    "Target-Date 2035",
    "Target-Date 2040",
    "Target-Date 2045",
    "Target-Date 2050",
    "Target-Date 2055",
    "Target-Date 2060+",
    "Target-Date Retirement",
    "Technology",
    "Trading - Leveraged/Inverse Commodities",
    "Trading - Leveraged/Inverse Equity",
    "Trading - Inverse Equity",
    "Trading - Leveraged Equity",
    "Ultrashort Bond",
    "Utilities",
    "World Allocation",
    "World Bond",
    "World Stock",
}
