PEER_GROUPS = {
    "US Fund Equity Energy",
    "US CE Convertibles",
    "EAA CE UK Large-Cap Equity",
    "EAA CE Other",
    "US Fund Financial",
    "India CE Multi-Cap",
    "US Fund Foreign Large Blend",
    "US Fund Consumer Cyclical",
    "EAA Fund Global Equity Income",
    "China Fund Sector Equity Financial and Real Estate",
    "US Fund Equity Precious Metals",
    "EAA Fund RMB Bond - Onshore",
    "China Fund QDII Greater China Equity",
    "US Fund Large Growth",
    "EAA Fund Germany Equity",
    "EAA Fund Hong Kong Equity",
    "EAA CE UK Small-Cap Equity",
    "US Fund Natural Resources",
    "US CE Preferred Stock",
    "India Fund Sector - Financial Services",
    "US Fund Diversified Emerging Mkts",
    "EAA Fund South Africa & Namibia Equity",
    "China Fund QDII Sector Equity",
    "EAA CE Sector Equity Biotechnology",
    "EAA Fund Switzerland Equity",
    "US Fund Large Value",
    "EAA Fund Asia ex-Japan Equity",
    "US Fund Health",
    "US Fund China Region",
    "EAA Fund Emerging Europe ex-Russia Equity",
    "EAA Fund Sector Equity Industrial Materials",
    "EAA Fund Japan Large-Cap Equity",
    "EAA Fund EUR Corporate Bond",
    "US Fund Technology",
    "EAA CE Global Large-Cap Blend Equity",
    "Mexico Fund Mexico Equity",
    "US Fund Trading--Leveraged Equity",
    "EAA Fund Sector Equity Consumer Goods & Services",
    "US Fund Large Blend",
    "EAA Fund Global Flex-Cap Equity",
    "EAA Fund EUR Aggressive Allocation - Global",
    "EAA Fund China Equity",
    "EAA Fund Global Large-Cap Growth Equity",
    "US CE Options-based",
    "EAA Fund Sector Equity Financial Services",
    "EAA Fund Europe Large-Cap Blend Equity",
    "EAA Fund China Equity - A Shares",
    "EAA Fund USD Corporate Bond",
    "EAA Fund Eurozone Large-Cap Equity",
    "China Fund Aggressive Allocation Fund",
    "EAA Fund Sector Equity Technology",
    "EAA Fund Global Emerging Markets Equity",
    "EAA Fund EUR Moderate Allocation - Global",
    "EAA Fund Other Bond",
    "EAA Fund Denmark Equity",
    "EAA Fund US Large-Cap Blend Equity",
    "India Fund Large-Cap",
    "Paper & Forestry",
    "Containers & Packaging",
    "US Fund Miscellaneous Region",
    "Energy Services",
    "EAA Fund Other Equity",
    "Homebuilders",
    "Construction Materials",
    "China Fund Equity Funds",
    "Steel",
    "Consumer Durables",
    "EAA Fund Global Large-Cap Blend Equity",
    "Transportation Infrastructure",
    "Precious Metals",
    "Building Products",
    "Traders & Distributors",
    "Electrical Equipment",
    "Auto Components",
    "Construction & Engineering",
    "Aerospace & Defense",
    "Refiners & Pipelines",
    "Diversified Metals",
    "Textiles & Apparel",
    "Industrial Conglomerates",
    "Household Products",
    "Commercial Services",
    "Food Retailers",
    "Semiconductors",
    "Media",
    "Automobiles",
    "Consumer Services",
    "Technology Hardware",
    "Transportation",
    "Telecommunication Services",
    "Oil & Gas Producers",
    "Machinery",
    "Retailing",
    "Healthcare",
    "Chemicals",
    "Food Products",
    "Diversified Financials",
    "Real Estate",
    "Insurance",
    "Utilities",
    "Pharmaceuticals",
    "Software & Services",
    "Banks",
}
