REGION_CODE_MAPPING = {
    "Argentina": "ar",
    "Australia": "au",
    "Austria": "at",
    "Belgium": "be",
    "Brazil": "br",
    "Canada": "ca",
    "Chile": "cl",
    "China": "cn",
    "Colombia": "co",
    "Czechia": "cz",
    "Denmark": "dk",
    "Egypt": "eg",
    "Estonia": "ee",
    "Finland": "fi",
    "France": "fr",
    "Germany": "de",
    "Greece": "gr",
    "Hong Kong": "hk",
    "Hungary": "hu",
    "Iceland": "is",
    "India": "in",
    "Indonesia": "id",
    "Ireland": "ie",
    "Israel": "il",
    "Italy": "it",
    "Japan": "jp",
    "Kuwait": "kw",
    "Latvia": "lv",
    "Lithuania": "lt",
    "Malaysia": "my",
    "Mexico": "mx",
    "Netherlands": "nl",
    "New Zealand": "nz",
    "Norway": "no",
    "Pakistan": "pk",
    "Peru": "pe",
    "Philippines": "ph",
    "Poland": "pl",
    "Portugal": "pt",
    "Qatar": "qa",
    "Romania": "ro",
    "Russia": "ru",
    "Saudi Arabia": "sa",
    "Singapore": "sg",
    "South Africa": "za",
    "South Korea": "kr",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Suriname": "sr",
    "Sweden": "se",
    "Switzerland": ["ch", "sw"],
    "Taiwan": "tw",
    "Thailand": "th",
    "Turkey": "tr",
    "United Arab Emirates": "ae",
    "United Kingdom": "gb",
    "United States": "us",
    "Venezuela": "ve",
    "Vietnam": "vn",
}
