_QUERY1_URL_ = "https://query1.finance.yahoo.com"
_BASE_URL_ = "https://query2.finance.yahoo.com"
_ROOT_URL_ = "https://finance.yahoo.com"

_SENTINEL_ = object()

fundamentals_keys = {
    "financials": [
        "TaxEffectOfUnusualItems",
        "TaxRateForCalcs",
        "NormalizedEBITDA",
        "NormalizedDilutedEPS",
        "NormalizedBasicEPS",
        "TotalUnusualItems",
        "TotalUnusualItemsExcludingGoodwill",
        "NetIncomeFromContinuingOperationNetMinorityInterest",
        "ReconciledDepreciation",
        "ReconciledCostOfRevenue",
        "EBITDA",
        "EBIT",
        "NetInterestIncome",
        "InterestExpense",
        "InterestIncome",
        "ContinuingAndDiscontinuedDilutedEPS",
        "ContinuingAndDiscontinuedBasicEPS",
        "NormalizedIncome",
        "NetIncomeFromContinuingAndDiscontinuedOperation",
        "TotalExpenses",
        "RentExpenseSupplemental",
        "ReportedNormalizedDilutedEPS",
        "ReportedNormalizedBasicEPS",
        "TotalOperatingIncomeAsReported",
        "DividendPerShare",
        "DilutedAverageShares",
        "BasicAverageShares",
        "DilutedEPS",
        "DilutedEPSOtherGainsLosses",
        "TaxLossCarryforwardDilutedEPS",
        "DilutedAccountingChange",
        "DilutedExtraordinary",
        "DilutedDiscontinuousOperations",
        "DilutedContinuousOperations",
        "BasicEPS",
        "BasicEPSOtherGainsLosses",
        "TaxLossCarryforwardBasicEPS",
        "BasicAccountingChange",
        "BasicExtraordinary",
        "BasicDiscontinuousOperations",
        "BasicContinuousOperations",
        "DilutedNIAvailtoComStockholders",
        "AverageDilutionEarnings",
        "NetIncomeCommonStockholders",
        "OtherunderPreferredStockDividend",
        "PreferredStockDividends",
        "NetIncome",
        "MinorityInterests",
        "NetIncomeIncludingNoncontrollingInterests",
        "NetIncomeFromTaxLossCarryforward",
        "NetIncomeExtraordinary",
        "NetIncomeDiscontinuousOperations",
        "NetIncomeContinuousOperations",
        "EarningsFromEquityInterestNetOfTax",
        "TaxProvision",
        "PretaxIncome",
        "OtherIncomeExpense",
        "OtherNonOperatingIncomeExpenses",
        "SpecialIncomeCharges",
        "GainOnSaleOfPPE",
        "GainOnSaleOfBusiness",
        "OtherSpecialCharges",
        "WriteOff",
        "ImpairmentOfCapitalAssets",
        "RestructuringAndMergernAcquisition",
        "SecuritiesAmortization",
        "EarningsFromEquityInterest",
        "GainOnSaleOfSecurity",
        "NetNonOperatingInterestIncomeExpense",
        "TotalOtherFinanceCost",
        "InterestExpenseNonOperating",
        "InterestIncomeNonOperating",
        "OperatingIncome",
        "OperatingExpense",
        "OtherOperatingExpenses",
        "OtherTaxes",
        "ProvisionForDoubtfulAccounts",
        "DepreciationAmortizationDepletionIncomeStatement",
        "DepletionIncomeStatement",
        "DepreciationAndAmortizationInIncomeStatement",
        "Amortization",
        "AmortizationOfIntangiblesIncomeStatement",
        "DepreciationIncomeStatement",
        "ResearchAndDevelopment",
        "SellingGeneralAndAdministration",
        "SellingAndMarketingExpense",
        "GeneralAndAdministrativeExpense",
        "OtherGandA",
        "InsuranceAndClaims",
        "RentAndLandingFees",
        "SalariesAndWages",
        "GrossProfit",
        "CostOfRevenue",
        "TotalRevenue",
        "ExciseTaxes",
        "OperatingRevenue",
        "LossAdjustmentExpense",
        "NetPolicyholderBenefitsAndClaims",
        "PolicyholderBenefitsGross",
        "PolicyholderBenefitsCeded",
        "OccupancyAndEquipment",
        "ProfessionalExpenseAndContractServicesExpense",
        "OtherNonInterestExpense",
    ],
    "balance-sheet": [
        "TreasurySharesNumber",
        "PreferredSharesNumber",
        "OrdinarySharesNumber",
        "ShareIssued",
        "NetDebt",
        "TotalDebt",
        "TangibleBookValue",
        "InvestedCapital",
        "WorkingCapital",
        "NetTangibleAssets",
        "CapitalLeaseObligations",
        "CommonStockEquity",
        "PreferredStockEquity",
        "TotalCapitalization",
        "TotalEquityGrossMinorityInterest",
        "MinorityInterest",
        "StockholdersEquity",
        "OtherEquityInterest",
        "GainsLossesNotAffectingRetainedEarnings",
        "OtherEquityAdjustments",
        "FixedAssetsRevaluationReserve",
        "ForeignCurrencyTranslationAdjustments",
        "MinimumPensionLiabilities",
        "UnrealizedGainLoss",
        "TreasuryStock",
        "RetainedEarnings",
        "AdditionalPaidInCapital",
        "CapitalStock",
        "OtherCapitalStock",
        "CommonStock",
        "PreferredStock",
        "TotalPartnershipCapital",
        "GeneralPartnershipCapital",
        "LimitedPartnershipCapital",
        "TotalLiabilitiesNetMinorityInterest",
        "TotalNonCurrentLiabilitiesNetMinorityInterest",
        "OtherNonCurrentLiabilities",
        "LiabilitiesHeldforSaleNonCurrent",
        "RestrictedCommonStock",
        "PreferredSecuritiesOutsideStockEquity",
        "DerivativeProductLiabilities",
        "EmployeeBenefits",
        "NonCurrentPensionAndOtherPostretirementBenefitPlans",
        "NonCurrentAccruedExpenses",
        "DuetoRelatedPartiesNonCurrent",
        "TradeandOtherPayablesNonCurrent",
        "NonCurrentDeferredLiabilities",
        "NonCurrentDeferredRevenue",
        "NonCurrentDeferredTaxesLiabilities",
        "LongTermDebtAndCapitalLeaseObligation",
        "LongTermCapitalLeaseObligation",
        "LongTermDebt",
        "LongTermProvisions",
        "CurrentLiabilities",
        "OtherCurrentLiabilities",
        "CurrentDeferredLiabilities",
        "CurrentDeferredRevenue",
        "CurrentDeferredTaxesLiabilities",
        "CurrentDebtAndCapitalLeaseObligation",
        "CurrentCapitalLeaseObligation",
        "CurrentDebt",
        "OtherCurrentBorrowings",
        "LineOfCredit",
        "CommercialPaper",
        "CurrentNotesPayable",
        "PensionandOtherPostRetirementBenefitPlansCurrent",
        "CurrentProvisions",
        "PayablesAndAccruedExpenses",
        "CurrentAccruedExpenses",
        "InterestPayable",
        "Payables",
        "OtherPayable",
        "DuetoRelatedPartiesCurrent",
        "DividendsPayable",
        "TotalTaxPayable",
        "IncomeTaxPayable",
        "AccountsPayable",
        "TotalAssets",
        "TotalNonCurrentAssets",
        "OtherNonCurrentAssets",
        "DefinedPensionBenefit",
        "NonCurrentPrepaidAssets",
        "NonCurrentDeferredAssets",
        "NonCurrentDeferredTaxesAssets",
        "DuefromRelatedPartiesNonCurrent",
        "NonCurrentNoteReceivables",
        "NonCurrentAccountsReceivable",
        "FinancialAssets",
        "InvestmentsAndAdvances",
        "OtherInvestments",
        "InvestmentinFinancialAssets",
        "HeldToMaturitySecurities",
        "AvailableForSaleSecurities",
        "FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal",
        "TradingSecurities",
        "LongTermEquityInvestment",
        "InvestmentsinJointVenturesatCost",
        "InvestmentsInOtherVenturesUnderEquityMethod",
        "InvestmentsinAssociatesatCost",
        "InvestmentsinSubsidiariesatCost",
        "InvestmentProperties",
        "GoodwillAndOtherIntangibleAssets",
        "OtherIntangibleAssets",
        "Goodwill",
        "NetPPE",
        "AccumulatedDepreciation",
        "GrossPPE",
        "Leases",
        "ConstructionInProgress",
        "OtherProperties",
        "MachineryFurnitureEquipment",
        "BuildingsAndImprovements",
        "LandAndImprovements",
        "Properties",
        "CurrentAssets",
        "OtherCurrentAssets",
        "HedgingAssetsCurrent",
        "AssetsHeldForSaleCurrent",
        "CurrentDeferredAssets",
        "CurrentDeferredTaxesAssets",
        "RestrictedCash",
        "PrepaidAssets",
        "Inventory",
        "InventoriesAdjustmentsAllowances",
        "OtherInventories",
        "FinishedGoods",
        "WorkInProcess",
        "RawMaterials",
        "Receivables",
        "ReceivablesAdjustmentsAllowances",
        "OtherReceivables",
        "DuefromRelatedPartiesCurrent",
        "TaxesReceivable",
        "AccruedInterestReceivable",
        "NotesReceivable",
        "LoansReceivable",
        "AccountsReceivable",
        "AllowanceForDoubtfulAccountsReceivable",
        "GrossAccountsReceivable",
        "CashCashEquivalentsAndShortTermInvestments",
        "OtherShortTermInvestments",
        "CashAndCashEquivalents",
        "CashEquivalents",
        "CashFinancial",
        "CashCashEquivalentsAndFederalFundsSold",
    ],
    "cash-flow": [
        "ForeignSales",
        "DomesticSales",
        "AdjustedGeographySegmentData",
        "FreeCashFlow",
        "RepurchaseOfCapitalStock",
        "RepaymentOfDebt",
        "IssuanceOfDebt",
        "IssuanceOfCapitalStock",
        "CapitalExpenditure",
        "InterestPaidSupplementalData",
        "IncomeTaxPaidSupplementalData",
        "EndCashPosition",
        "OtherCashAdjustmentOutsideChangeinCash",
        "BeginningCashPosition",
        "EffectOfExchangeRateChanges",
        "ChangesInCash",
        "OtherCashAdjustmentInsideChangeinCash",
        "CashFlowFromDiscontinuedOperation",
        "FinancingCashFlow",
        "CashFromDiscontinuedFinancingActivities",
        "CashFlowFromContinuingFinancingActivities",
        "NetOtherFinancingCharges",
        "InterestPaidCFF",
        "ProceedsFromStockOptionExercised",
        "CashDividendsPaid",
        "PreferredStockDividendPaid",
        "CommonStockDividendPaid",
        "NetPreferredStockIssuance",
        "PreferredStockPayments",
        "PreferredStockIssuance",
        "NetCommonStockIssuance",
        "CommonStockPayments",
        "CommonStockIssuance",
        "NetIssuancePaymentsOfDebt",
        "NetShortTermDebtIssuance",
        "ShortTermDebtPayments",
        "ShortTermDebtIssuance",
        "NetLongTermDebtIssuance",
        "LongTermDebtPayments",
        "LongTermDebtIssuance",
        "InvestingCashFlow",
        "CashFromDiscontinuedInvestingActivities",
        "CashFlowFromContinuingInvestingActivities",
        "NetOtherInvestingChanges",
        "InterestReceivedCFI",
        "DividendsReceivedCFI",
        "NetInvestmentPurchaseAndSale",
        "SaleOfInvestment",
        "PurchaseOfInvestment",
        "NetInvestmentPropertiesPurchaseAndSale",
        "SaleOfInvestmentProperties",
        "PurchaseOfInvestmentProperties",
        "NetBusinessPurchaseAndSale",
        "SaleOfBusiness",
        "PurchaseOfBusiness",
        "NetIntangiblesPurchaseAndSale",
        "SaleOfIntangibles",
        "PurchaseOfIntangibles",
        "NetPPEPurchaseAndSale",
        "SaleOfPPE",
        "PurchaseOfPPE",
        "CapitalExpenditureReported",
        "OperatingCashFlow",
        "CashFromDiscontinuedOperatingActivities",
        "CashFlowFromContinuingOperatingActivities",
        "TaxesRefundPaid",
        "InterestReceivedCFO",
        "InterestPaidCFO",
        "DividendReceivedCFO",
        "DividendPaidCFO",
        "ChangeInWorkingCapital",
        "ChangeInOtherWorkingCapital",
        "ChangeInOtherCurrentLiabilities",
        "ChangeInOtherCurrentAssets",
        "ChangeInPayablesAndAccruedExpense",
        "ChangeInAccruedExpense",
        "ChangeInInterestPayable",
        "ChangeInPayable",
        "ChangeInDividendPayable",
        "ChangeInAccountPayable",
        "ChangeInTaxPayable",
        "ChangeInIncomeTaxPayable",
        "ChangeInPrepaidAssets",
        "ChangeInInventory",
        "ChangeInReceivables",
        "ChangesInAccountReceivables",
        "OtherNonCashItems",
        "ExcessTaxBenefitFromStockBasedCompensation",
        "StockBasedCompensation",
        "UnrealizedGainLossOnInvestmentSecurities",
        "ProvisionandWriteOffofAssets",
        "AssetImpairmentCharge",
        "AmortizationOfSecurities",
        "DeferredTax",
        "DeferredIncomeTax",
        "DepreciationAmortizationDepletion",
        "Depletion",
        "DepreciationAndAmortization",
        "AmortizationCashFlow",
        "AmortizationOfIntangibles",
        "Depreciation",
        "OperatingGainsLosses",
        "PensionAndEmployeeBenefitExpense",
        "EarningsLossesFromEquityInvestments",
        "GainLossOnInvestmentSecurities",
        "NetForeignCurrencyExchangeGainLoss",
        "GainLossOnSaleOfPPE",
        "GainLossOnSaleOfBusiness",
        "NetIncomeFromContinuingOperations",
        "CashFlowsfromusedinOperatingActivitiesDirect",
        "TaxesRefundPaidDirect",
        "InterestReceivedDirect",
        "InterestPaidDirect",
        "DividendsReceivedDirect",
        "DividendsPaidDirect",
        "ClassesofCashPayments",
        "OtherCashPaymentsfromOperatingActivities",
        "PaymentsonBehalfofEmployees",
        "PaymentstoSuppliersforGoodsandServices",
        "ClassesofCashReceiptsfromOperatingActivities",
        "OtherCashReceiptsfromOperatingActivities",
        "ReceiptsfromGovernmentGrants",
        "ReceiptsfromCustomers",
    ],
}

_PRICE_COLNAMES_ = ["Open", "High", "Low", "Close", "Adj Close"]

quote_summary_valid_modules = (
    "summaryProfile",  # contains general information about the company
    "summaryDetail",  # prices + volume + market cap + etc
    "assetProfile",  # summaryProfile + company officers
    "fundProfile",
    "price",  # current prices
    "quoteType",  # quoteType
    "esgScores",  # Environmental, social, and governance (ESG) scores, sustainability and ethical performance of companies
    "incomeStatementHistory",
    "incomeStatementHistoryQuarterly",
    "balanceSheetHistory",
    "balanceSheetHistoryQuarterly",
    "cashFlowStatementHistory",
    "cashFlowStatementHistoryQuarterly",
    "defaultKeyStatistics",  # KPIs (PE, enterprise value, EPS, EBITA, and more)
    "financialData",  # Financial KPIs (revenue, gross margins, operating cash flow, free cash flow, and more)
    "calendarEvents",  # future earnings date
    "secFilings",  # SEC filings, such as 10K and 10Q reports
    "upgradeDowngradeHistory",  # upgrades and downgrades that analysts have given a company's stock
    "institutionOwnership",  # institutional ownership, holders and shares outstanding
    "fundOwnership",  # mutual fund ownership, holders and shares outstanding
    "majorDirectHolders",
    "majorHoldersBreakdown",
    "insiderTransactions",  # insider transactions, such as the number of shares bought and sold by company executives
    "insiderHolders",  # insider holders, such as the number of shares held by company executives
    "netSharePurchaseActivity",  # net share purchase activity, such as the number of shares bought and sold by company executives
    "earnings",  # earnings history
    "earningsHistory",
    "earningsTrend",  # earnings trend
    "industryTrend",
    "indexTrend",
    "sectorTrend",
    "recommendationTrend",
    "futuresChain",
)

# map last updated as of 2024.09.18
SECTOR_INDUSTRY_MAPPING = {
    "Basic Materials": {
        "Specialty Chemicals",
        "Gold",
        "Building Materials",
        "Copper",
        "Steel",
        "Agricultural Inputs",
        "Chemicals",
        "Other Industrial Metals & Mining",
        "Lumber & Wood Production",
        "Aluminum",
        "Other Precious Metals & Mining",
        "Coking Coal",
        "Paper & Paper Products",
        "Silver",
    },
    "Communication Services": {
        "Advertising Agencies",
        "Broadcasting",
        "Electronic Gaming & Multimedia",
        "Entertainment",
        "Internet Content & Information",
        "Publishing",
        "Telecom Services",
    },
    "Consumer Cyclical": {
        "Apparel Manufacturing",
        "Apparel Retail",
        "Auto & Truck Dealerships",
        "Auto Manufacturers",
        "Auto Parts",
        "Department Stores",
        "Footwear & Accessories",
        "Furnishings, Fixtures & Appliances",
        "Gambling",
        "Home Improvement Retail",
        "Internet Retail",
        "Leisure",
        "Lodging",
        "Luxury Goods",
        "Packaging & Containers",
        "Personal Services",
        "Recreational Vehicles",
        "Residential Construction",
        "Resorts & Casinos",
        "Restaurants",
        "Specialty Retail",
        "Textile Manufacturing",
        "Travel Services",
    },
    "Consumer Defensive": {
        "Beverages - Brewers",
        "Beverages - Non-Alcoholic",
        "Beverages - Wineries & Distilleries",
        "Confectioners",
        "Discount Stores",
        "Education & Training Services",
        "Farm Products",
        "Food Distribution",
        "Grocery Stores",
        "Household & Personal Products",
        "Packaged Foods",
        "Tobacco",
    },
    "Energy": {
        "Oil Gas Drilling",
        "Oil Gas E P",
        "Oil Gas Equipment Services",
        "Oil Gas Integrated",
        "Oil Gas Midstream",
        "Oil Gas Refining Marketing",
        "Thermal Coal",
        "Uranium",
    },
    "Financial Services": {
        "Asset Management",
        "Banks Diversified",
        "Banks Regional",
        "Capital Markets",
        "Credit Services",
        "Financial Conglomerates",
        "Financial Data Stock Exchanges",
        "Insurance Brokers",
        "Insurance Diversified",
        "Insurance Life",
        "Insurance Property Casualty",
        "Insurance Reinsurance",
        "Insurance Specialty",
        "Mortgage Finance",
        "Shell Companies",
    },
    "Healthcare": {
        "Biotechnology",
        "Diagnostics Research",
        "Drug Manufacturers General",
        "Drug Manufacturers Specialty Generic",
        "Health Information Services",
        "Healthcare Plans",
        "Medical Care Facilities",
        "Medical Devices",
        "Medical Distribution",
        "Medical Instruments Supplies",
        "Pharmaceutical Retailers",
    },
    "Industrials": {
        "Aerospace Defense",
        "Airlines",
        "Airports Air Services",
        "Building Products Equipment",
        "Business Equipment Supplies",
        "Conglomerates",
        "Consulting Services",
        "Electrical Equipment Parts",
        "Engineering Construction",
        "Farm Heavy Construction Machinery",
        "Industrial Distribution",
        "Infrastructure Operations",
        "Integrated Freight Logistics",
        "Marine Shipping",
        "Metal Fabrication",
        "Pollution Treatment Controls",
        "Railroads",
        "Rental Leasing Services",
        "Security Protection Services",
        "Specialty Business Services",
        "Specialty Industrial Machinery",
        "Staffing Employment Services",
        "Tools Accessories",
        "Trucking",
        "Waste Management",
    },
    "Real Estate": {
        "Real Estate Development",
        "Real Estate Diversified",
        "Real Estate Services",
        "Reit Diversified",
        "Reit Healthcare Facilities",
        "Reit Hotel Motel",
        "Reit Industrial",
        "Reit Mortgage",
        "Reit Office",
        "Reit Residential",
        "Reit Retail",
        "Reit Specialty",
    },
    "Technology": {
        "Communication Equipment",
        "Computer Hardware",
        "Consumer Electronics",
        "Electronic Components",
        "Electronics Computer Distribution",
        "Information Technology Services",
        "Scientific Technical Instruments",
        "Semiconductor Equipment Materials",
        "Semiconductors",
        "Software Application",
        "Software Infrastructure",
        "Solar",
    },
    "Utilities": {
        "Utilities Diversified",
        "Utilities Independent Power Producers",
        "Utilities Regulated Electric",
        "Utilities Regulated Gas",
        "Utilities Regulated Water",
        "Utilities Renewable",
    },
}
SECTOR_INDUSTRY_MAPPING_LC = {}
for k in SECTOR_INDUSTRY_MAPPING.keys():
    k2 = (
        k.lower()
        .replace("& ", "")
        .replace("- ", "")
        .replace(", ", " ")
        .replace(" ", "-")
    )
    SECTOR_INDUSTRY_MAPPING_LC[k2] = []
    for v in SECTOR_INDUSTRY_MAPPING[k]:
        v2 = (
            v.lower()
            .replace("& ", "")
            .replace("- ", "")
            .replace(", ", " ")
            .replace(" ", "-")
        )
        SECTOR_INDUSTRY_MAPPING_LC[k2].append(v2)

# _MIC_TO_YAHOO_SUFFIX maps Market Identifier Codes (MIC) to Yahoo Finance market suffixes.
# c.f. :
# https://help.yahoo.com/kb/finance-for-web/SLN2310.html;_ylt=AwrJKiCZFo9g3Y8AsDWPAwx.;_ylu=Y29sbwMEcG9zAzEEdnRpZAMEc2VjA3Ny?locale=en_US
# https://www.iso20022.org/market-identifier-codes

_MIC_TO_YAHOO_SUFFIX = {
    "XCBT": "CBT",
    "XCME": "CME",
    "IFUS": "NYB",
    "CECS": "CMX",
    "XNYM": "NYM",
    "XNYS": "",
    "XNAS": "",  # United States
    "XBUE": "BA",  # Argentina
    "XVIE": "VI",  # Austria
    "XASX": "AX",
    "XAUS": "XA",  # Australia
    "XBRU": "BR",  # Belgium
    "BVMF": "SA",  # Brazil
    "CNSX": "CN",
    "NEOE": "NE",
    "XTSE": "TO",
    "XTSX": "V",  # Canada
    "XSGO": "SN",  # Chile
    "XSHG": "SS",
    "XSHE": "SZ",  # China
    "XBOG": "CL",  # Colombia
    "XPRA": "PR",  # Czech Republic
    "XCSE": "CO",  # Denmark
    "XCAI": "CA",  # Egypt
    "XTAL": "TL",  # Estonia
    "CEUX": "XD",
    "XEUR": "NX",  # Europe (Cboe Europe, Euronext)
    "XHEL": "HE",  # Finland
    "XPAR": "PA",  # France
    "XBER": "BE",
    "XBMS": "BM",
    "XDUS": "DU",
    "XFRA": "F",
    "XHAM": "HM",
    "XHAN": "HA",
    "XMUN": "MU",
    "XSTU": "SG",
    "XETR": "DE",  # Germany
    "XATH": "AT",  # Greece
    "XHKG": "HK",  # Hong Kong
    "XBUD": "BD",  # Hungary
    "XICE": "IC",  # Iceland
    "XBOM": "BO",
    "XNSE": "NS",  # India
    "XIDX": "JK",  # Indonesia
    "XDUB": "IR",  # Ireland
    "XTAE": "TA",  # Israel
    "MTAA": "MI",
    "EUTL": "TI",  # Italy
    "XTKS": "T",  # Japan
    "XKFE": "KW",  # Kuwait
    "XRIS": "RG",  # Latvia
    "XVIL": "VS",  # Lithuania
    "XKLS": "KL",  # Malaysia
    "XMEX": "MX",  # Mexico
    "XAMS": "AS",  # Netherlands
    "XNZE": "NZ",  # New Zealand
    "XOSL": "OL",  # Norway
    "XPHS": "PS",  # Philippines
    "XWAR": "WA",  # Poland
    "XLIS": "LS",  # Portugal
    "XQAT": "QA",  # Qatar
    "XBSE": "RO",  # Romania
    "XSES": "SI",  # Singapore
    "XJSE": "JO",  # South Africa
    "XKRX": "KS",
    "KQKS": "KQ",  # South Korea
    "BMEX": "MC",  # Spain
    "XTAD": "SAU",  # Saudi Arabia
    "XSTO": "ST",  # Sweden
    "XSWX": "SW",  # Switzerland
    "ROCO": "TWO",
    "XTAI": "TW",  # Taiwan
    "XBKK": "BK",  # Thailand
    "XIST": "IS",  # Turkey
    "XDFM": "AE",  # UAE
    "AQXE": "AQ",
    "XCHI": "XC",
    "XLON": "L",
    "ILSE": "IL",  # United Kingdom
    "XCAR": "CR",  # Venezuela
    "XSTC": "VN",  # Vietnam
}

USER_AGENTS = [
    # Chrome
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    # Firefox
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.7; rv:135.0) Gecko/20100101 Firefox/135.0",
    "Mozilla/5.0 (X11; Linux i686; rv:135.0) Gecko/20100101 Firefox/135.0",
    # Safari
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_7_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15",
    # Edge
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/131.0.2903.86",
]
